DELETE http://localhost:8080/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI1NzA3MzQ0LCJ1c2VySWQiOjJ9.KB6A_1CafpQNcIPmFLkTcCXIrLeheoQQXNk3QoL0PFY
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MjU3MDkyNjAsInVzZXJJZCI6MX0.RRaBffECEZuB6Xh4Pn9yPYdAiGgyZJHZPxYy7detZMs